---
abstract: 'Interface to the Google AJAX Search API and suggestion API (DEPRECATED)'
author:
  - 'Robert Krimen <robertkrimen@gmail.com>'
build_requires:
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Google-Search
requires:
  Any::Moose: 0
  Carp::Clan::Share: 0
  JSON: 2
  LWP::UserAgent: 0
  Try::Tiny: 0
  URI: 0
version: 0.028
